name: Deploy Staging



on:
  push:
    branches: [ deploy ]
jobs:
  deploy_staging:

    runs-on: ubuntu-latest

    steps:
      - name: test ssh connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAG_POPCORN_HOST }}
          username: ${{ secrets.POPCORN_USER }}
          key: ${{ secrets.POPCORN_SSH_PRIV }}
          port: ${{ secrets.STAG_POPCORN_PORT }}
          script: docker compose up -d